### PR TITLE
Add REST Auth token endpoints

### PR DESCRIPTION
**Pull request by hodossy**
I added the same workflow for the REST endpoint as the normal view, just returning the json data. This gives the posibility to use the same endpoints whether OAuth2 was implemented or an external service is used. Client side code can remain the same. Proposed request flow now:

Login endpoint -> Redirect to Auth provider -> redirect to callback -> return ID and tokens

Refreshes can also be made via the backend.

### CODE REVIEW

**Comment by hodossy** [comment]
I am working on the solution of the failing testcases. It seems however to be a django override_settings() bug.

**Comment by jobec** [comment]
Can you explain in a bit more detail what exactly was the issue you bumped into?

Because I have the feeling that it's falling outside the scope of this package.
Also, the fact that you sort of restructured the entire code base, makes it almost impossible to review this MR.

**Comment by hodossy** [comment]
[Docs] (https://docs.djangoproject.com/en/2.2/topics/testing/tools/#overriding-settings ) says that you can safely delete settings when using `@override_settings()`. It turns out that it can only restore the original settings if the whole attribute is deleted (since it is implemented based on `__delattr__` of the `settings` object, as per my understanding goes).

I have just made two things, I moved some common functions, that where previously a method to their own module, so I can reuse them in the rest views as well (`adfs.py` was born), and added two views to return rest responses for the callback and refresh views. Login view should redirect to the ADFS endpoint. To accomplish that, rest_framework became a module, but I kept backward compatibility.

**Comment by hodossy** [comment]
As I see, this only provides a way to decouple my front end app from the authentication service I use (as long as it can be access via an HTTP call), so I can keep a stable interface while also freely exchange the auth service for my API.

**Comment by jobec** [comment]
I don't feel like implementing this as it's against the principle of separating resource server (your API in this case) and the client (your, I presume, single page application).
In case of a REST API, the API is not it's own client, hence it's not the API's responsibility to get the access token.

in the situation of plain Django, Django is both the client and resource server.

See https://django-auth-adfs.readthedocs.io/en/latest/oauth2_explained.html

Did you look into https://github.com/davesque/django-rest-framework-simplejwt already? This might be what you are looking for.

**Pull request closed without merging**
