### PR TITLE
Add MIRROR_GROUP to mirror groups from ADFS

### PR DESCRIPTION
**Pull request by wreiner**
This parameter will create groups from ADFS in the Django database if they do not exist already like it is been done in django_auth_ldap.

### CODE REVIEW

**Comment by jobec** [comment]
I like the idea.

But could you rebase your changed on top of the `v1-rewrite` branch?
It contains quite some changes already and at the moment it makes no sense to merge your change into master.

**Comment by wreiner** [comment]
Sure, I'll look into it.

**Comment by wreiner** [comment]
@jobec sorry but I'm not sure what you mean by rebase my changes on top of v1-rewrite to be honest as Github tells me you already changed the base and I've never heard that request.
Should I create a new pull request for the v1-rewrite branch?

My changes should merge into v1-rewrite without a problem now after I fixed the merge conflict in the docs.

**Comment by jobec** [comment]
I'll take care of it.

But, fyi, asking a rebase means that you take another branch as the "base" of your changes and reapply the changes on top of that branch.

See here for an explanation: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

**Pull request merged**
