### PR TITLE
typo in readme file regarding CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by mislavcimpersak**
Just fixing a typo in README.rst

The file in repo is called `CONTRIBUTING.rst` and in readme file the name was `CONTRIBUTION.rst`.

### CODE REVIEW

**Comment by jobec** [comment]
If possible, briefly scan for some more typos in other files :-)

**Comment by mislavcimpersak** [comment]
No problem 👍 

I'll write here when I'm done.

**Comment by mislavcimpersak** [comment]
Done. Feel free to review it when you get the chance.

**Comment by jobec** [comment]
Nice job. Didn't know there were that many :)

It also looks like your editor (pycharm?) is set to shorter line lengths then mine (120 chars) because I see some split lines. Not that it matters, but I just noticed.

**Comment by mislavcimpersak** [comment]
Yeah, it's set to 80 chars per line. I just changed it in some comments just for good measure.

**Comment by mislavcimpersak** [comment]
Btw. if you get the time today please release 0.1.1 to pypi so I can update my test suite with new requirements.

Thanks 😃

**Comment by jobec** [comment]
0.1.1 released

**Pull request merged**
