### PR TITLE
support for `?next=` param (after login)

### PR DESCRIPTION
**Pull request by fopina**
Allow `next` field to be passed along with REDIR_URI to ADFS and update JWT token validation to consider it as well

### CODE REVIEW

**Comment by fopina** [comment]
As an alternative to #26  :)

**Comment by fopina** [comment]
forgot the tests sorry, I'll try to update them once I get some free time

**Comment by fopina** [comment]
There, tests updated for full coverage. Just noticed that this PR also closes #18

**Comment by jobec** [comment]
Before accepting the pull request, can you change it so the URL is passed as a base64 encoded value in the `state` parameter as specified in the [OAuth2 RFC](https://tools.ietf.org/html/rfc6749#section-4.1.1)?

I've got plans to also support the OpenID Connect featured of ADFS 4.0 on windows 2016. And there also this state parameter is a recommended one.

**Comment by fopina** [comment]
Ok.. but any GET parameters in the `redirect_uri` are passed by in the redirect so this is compliant as well, I'm not entirely sure the purpose of `state` would be that (nor if it is supported in ADFS 3.0).
I'll try to check once I have time, as this is currently working and in PROD (using my fork as dependency)

**Comment by jobec** [comment]
Well, true, it's a bit open for discussion...
```
   state
         RECOMMENDED.  An opaque value used by the client to maintain
         state between the request and callback.  The authorization
         server includes this value when redirecting the user-agent back
         to the client.  The parameter SHOULD be used for preventing
         cross-site request forgery as described in Section 10.12.
```
Still, in part is seems to be usable for it.

**Comment by jobec** [comment]
After some more research, it seems there is already a potential issue in the current code.

Contrary to my understanding, while testing I found out ADFS only checks if the redirect URI starts with whatever was registered. Not whether it's a full match. So if you register the redirect URI `https://mysite.com/oauth2/login` it will also accept `https://mysite.com/oauth2/login?next=/article/123`. Or even `https://mysite.com/oauth2/login/some/sub/page`

This should already allow the use of the Django built-in `next` parameter. But indicates that `state` parameter is needed to stop a potential CSRF attack.

**Comment by fopina** [comment]
Yes, it only checks if it starts with, not full match, that’s why I do have it working like this.
Related to CSRF, i understand what you mean, though any GET in the app that changes DB without a CSRF token it’s an attack vector any time. It’s not created by ADFS module, the only thing it changes is that user does not need to have open session.
Though the CSRF already existed and needed fixing.
Then there could be the open redirect issue though that is indeed validated by Django in the “next” parameter, though not covered in the OauthView() in my PR here though.. that I can look into.
But CSRF is not an issue nor an existing CSRF can be minimized by anything done here..
The loginrequired step always redirects to SSO, so there’s no “token” we can put there that wouldn’t apply to any given link without the token..

**Comment by fopina** [comment]
There, I think this is better now, indeed. `state` makes it cleaner (as it is not part of the jwt token validation, backend.py change is not required), and also added `is_safe_url` check to avoid open redirects (same check as in django auth)

**Comment by jobec** [comment]
Just a FYI: I'm not ignoring the merge request. I'm actually in the process of drastically updating this package to make things more automatic.

Once I'm done with that, I'll see how this merge request fits in.

I'm doing this because I received too many questions about how to get this package working. So my goal is to both give users a full example environment in the form of a Vagrant environment, docs for both windows 2012 and 2016 and automatic detection of parameters as much as possible (based on data in the request and data in the ADFS metadata file)

**Comment by fopina** [comment]
No problem, I have it working as I needed :)

PS: you should tell those people to go RTFM as you made quite easy to read docs. I was not familiar with ADFS at all, finding your package and checking the docs was enough to use it *including* the ADFS server setup...

**Comment by jobec** [comment]
Well, it's not always that easy :)

The topic of ADFS "is" confusing. The moment you have a slightly different situation then the one I describe, you're in trouble and sometimes it can be difficult to troubleshoot...

Also a FYI:
I'll be adding Azure AD support and Azure AD seems not to support the `next` parameter... :-( Nor does is support the nonce parameter. Or at least I can't get it to work...

**Comment by jobec** [comment]
Ok... Ignore that idea of adding Azure AD support... It doesn't allow you to set specific claims like the list of group names. Rendering it rather useless.

**Comment by fopina** [comment]
Yes, I started the whole thing for integrating the app in MyApps and Azure AD, resulting in not understanding at all what’s “azure ad” and ending up registering the app as external in my apps and simply  using ADFS

**Comment by jobec** [comment]
Meanwhile, this is fixed in the `v1-rewrite` branch. It now always returns back to the page triggering the login. Both when using the LoginRequiredMiddleware or when decorating views with `LoginRequired`

**Pull request closed without merging**
