### PR TITLE
Integrity error (#93)

### LINKED ISSUE #93: Database Integrity Error when using multiple workers/threads with Gunicorn
I'm developing a [middleware](https://github.com/JonasKs/django-guid/tree/skip_cleanup) where I store a GUID for each request and was doing tests on how this performs with gunicorn settings such as `--threads 4` and `-w 4`. ([Docs](https://docs.gunicorn.org/en/stable/settings.html))

Together with this, I do a lot of requests with [`ab`](https://httpd.apache.org/docs/2.4/programs/ab.html). Example string: `ab -p post.txt -c 4 -n 50 -T application/json -H "Authorization: Bearer <access_token> http://127.0.0.1:8000/api/v1/test`

This means I'm sending concurrent requests towards the Django app, which now has multiple threads instead of the sync single threaded default Gunicorn settings. Now, with my middleware it's easy to track each request and when things goes wrong: (Filtered out GUID `55f7b768046149e5aecf723cbbb053b4`) 

```py
INFO 2020-01-10 14:13:20,188 [None] django_guid.middleware No Correlation-ID found in the header. Added Correlation-ID: 55f7b768046149e5aecf723cbbb053b4
WARNING 2020-01-10 14:13:20,282 [55f7b768046149e5aecf723cbbb053b4] django_auth_adfs Claim 'family_name' for user field 'last_name' was not found in the access token for user 'MyUser'. Field is not required and will be left empty
WARNING 2020-01-10 14:13:20,284 [55f7b768046149e5aecf723cbbb053b4] django_auth_adfs Claim 'email' for user field 'email' was not found in the access token for user 'MyUser'. Field is not required and will be left empty
ERROR 2020-01-10 14:13:20,337 [55f7b768046149e5aecf723cbbb053b4] django.request Internal Server Error: /api/v1/apic/flash
Traceback (most recent call last):
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '25-680' for key 'auth_user_groups_user_id_group_id_94350c0c_uniq'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/request.py", line 373, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django_auth_adfs/rest_framework.py", line 40, in authenticate
    user = authenticate(access_token=auth[1])
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django_auth_adfs/backend.py", line 285, in authenticate
    user = self.process_access_token(access_token)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django_auth_adfs/backend.py", line 95, in process_access_token
    self.update_user_groups(user, claims)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django_auth_adfs/backend.py", line 201, in update_user_groups
    user.groups.add(group)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 936, in add
    self._add_items(
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1080, in _add_items
    self.through._default_manager.using(db).bulk_create([
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/query.py", line 474, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1211, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '25-680' for key 'auth_user_groups_user_id_group_id_94350c0c_uniq'")

```

EDIT: I assume this potentially can happen in a loadbalanced environment (such as a multi-pod kubernetes set up) too.

### PR DESCRIPTION
**Pull request by JonasKs**
Attempt to fix #93. All tests pass and I've confirmed that it works locally. 

Please let me know if you have any concerns or comments.

### CODE REVIEW

**Comment by JonasKs** [comment]
I have figured that the _real_ reason this would happen so often to us is because of a group name in AD being changed from `myGroup` to `MyGroup` in PascalCase.
```py
groups_to_remove = set(django_groups) - set(claim_groups)
groups_to_add = set(claim_groups) - set(django_groups)
``` 
it would result in the following:
```bash
DEBUG 2020-01-21 11:04:26,562 django_auth_adfs User removed from group 'myGroup'
DEBUG 2020-01-21 11:04:26,564 django_auth_adfs Created group 'MyGroup'
DEBUG 2020-01-21 11:04:26,575 django_auth_adfs User added to group 'MyGroup'
``` 
In other words, on _every_ request to the site, it would do a full clean, making it get an `IntegrityError` very often.

I you'd like, we could rather raise a different PR that simply does this:
```py
case_insensitive_django_groups = set(group.lower() for group in django_groups)
case_insensitive_claim_groups = set(group.lower() for group in claim_groups)
```

How ever, I have made the checks case insensitive when looking for groups.

**Comment by jobec** [comment]
It depends whether Django's group names are case sensitive or not. And whether there are situation where it could be case sensitive (e.g. when someone extends django's authentication).

**Comment by jobec** [comment]
Looking at the logs you posted, it does look like Django's groups are case insensitive themselves:

https://github.com/jobec/django-auth-adfs/blob/1e930661cc1cb6d9c9321c512a2bb4faac4f7ded/django_auth_adfs/backend.py#L198

The code determines the group needs to be deleted, but when "creating" the group, it actually retrieves the one with the lower case `my` again and adds the user to that group.

Strange... That's quite an unexpected quirk from Django.

**Comment by JonasKs** [comment]
You are correct.

If I do `Group.objects.get(name='mygroup')` in all lower case, it will still fetch the correct group:

```py
>>> Group.objects.get(name='mygroup')
<Group: MyGroup>
```

**Comment by jobec** [comment]
Let me see where this case insensitivity comes from. I always though you need to do it explicitly with [`iexact`](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#std:fieldlookup-iexact)

**Comment by jobec** [comment]
When I test, getting groups by name **is** case sensitive. So it looks like something modified the behavior of you Django setup

What is your Django version? What other packages did you install? What other apps are activated in Django?

**Comment by JonasKs** [comment]
Wait, that's really interesting.

I tested on my [`django-guid`](https://github.com/JonasKs/django-guid) project now, except that I changed the database to be a `MySQL` database, it is in my real environment:
```py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'PASSWORD': '',
        'NAME': 'django-adfs-test',
        'USER': 'test',
    },
}
```

```py
from django.contrib.auth.models import Group
Group.objects.get_or_create(name="MyTestGroup")
(<Group: MyTestGroup>, True)
Group.objects.get(name="MyTestGroup")
<Group: MyTestGroup>
Group.objects.get(name="MyTestGROUP")
<Group: MyTestGroup>
```
How ever, with a `sqlit3` database:

```py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```

```py
from django.contrib.auth.models import Group
Group.objects.get_or_create(name="MyTestGroup")
(<Group: MyTestGroup>, True)
Group.objects.get(name="MyTestGroup")
<Group: MyTestGroup>
Group.objects.get(name="MyTestGROUP")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/aa545@i04.local/Documents/projects/personal/django-guid/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aa545@i04.local/Documents/projects/personal/django-guid/venv/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

```

**Comment by jobec** [comment]
Looks like it's a "feature" of MySQL:

https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html

**Comment by JonasKs** [comment]
Yeah, in Django I can do this (when I run my tests):

```py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'PASSWORD': '',
        'NAME': 'django-adfs-test',
        'USER': 'test',
        'TEST': {
            'NAME': 'nsportal-test',
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_0900_as_cs',
        },
    },
}
```

Now, the question still stand though. Since multiple groups with different case sensitivity is not possible in AD(`MyGroup` and `MyGROUP` can not exist at the same time), should the check be case insensitive when matching groups? Or should one have it case sensitive and potentially have unused groups in the database?

**Comment by jobec** [comment]
To recap:
* You pre-created groups in django, according to it's name in AD.
* ADFS changes the group names to pascal case
* Because of this, you group names in django don't match in django-auth-adfs's code, but the undelaying database is case-insensitive, causing the group with the incorrect case to match instead of creating a new group

The missing link here, is "why" ADFS changes the group name. Are you sure the field ADFS uses as the group's name is the same as what you used to create the groups initially?

Ideally, the groups you create in Django would match with what ADFS sends back.
Maybe getting the groups with an `_iexact` and giving an error when we get 2 results, might be a workaround.

**Comment by JonasKs** [comment]
Recap:

* User logged into my site, groups were created
* A letter in a group name was changed in AD from upper case to lower case  
* User logged into the site again, group name now differs.
* Because of my case insensitive database, this became an issue. For people with case sensitive databses, this wouldn't have been an issue.

I have no strong feelings about a solution here, I can fix the tables on my end and add a little note in your documentation about this for MySQL users.

**Comment by jobec** [comment]
My preference goes to an entry in the FAQ to be honest.

If you get this error, then...

**Comment by JonasKs** [comment]
Perfect. I'll document it in the FAQ after work or tomorrow if you don't mind. 

The rest of the code, any comments on that?

**Comment by jobec** [comment]
Remove the lower case changes and I'll have another look.

**Comment by JonasKs** [comment]
Added docs. In case you don't want to pull to build them, here's how it looks:

image

**Comment by JonasKs** [comment]
Any thoughts or comments?

**Comment by JonasKs** [comment]
This is still causing issues for us. Did you end up checking out the solution? :)

**Comment by sondrelg** [comment]
We're experiencing a lot of these errors (same company but different projects). 

Would really appreciate if this could be looked at soon, as we're currently forced to switch to Jonas' fork, just based on the number of errors we're seeing from this in production.

**Pull request merged**
