### PR TITLE
Redirect back to the page that triggered the login

### PR DESCRIPTION
**Pull request by user1725**

### CODE REVIEW

**Comment by jobec** [comment]
I'll need a bit more time to properly review this.

**Comment by fopina** [comment]
I'm currently updating my fork to support this as well, but I'm actually adding `?next` to `settings.REDIR_URI` as ADFS does not complain about extra GET params and does send them back.

Updating backend is still required as JWT validation of the code requires the full redirect_uri used.

Not sure which option is cleaner, but as Django even supports passing the actual `request` to the backend, I'd say there's no need for cookie.

**Comment by jobec** [comment]
Can you confirm that you are running ADFS 3.0 on windows server 2012?
I know ADFS 4.0 on 2016 indeed does that.

I was about to implement the [`state` parameter of openID connect](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest). But I'm not sure ADFS 3.0 supports this. (As I don't have access to a ADFS 3.0 environment right now. Need to rebuild my lab)

**Comment by jobec** [comment]
Also, please don't combine 2 issues in the same pull request. Make a separate pull request for it.

**Comment by fopina** [comment]
I'm doing this on ADFS 3.0 running on 2012 R2 yes. But not using the `state` parameter, maybe that's cleaner..

**Comment by fopina** [comment]
@jobec Not sure which two issues I’ve combined, let me know and I’ll split them

**Comment by jobec** [comment]
No worries. Other stuff is merged already.

**Comment by jobec** [comment]
Fixed in v1-rewrite branch.

**Pull request closed without merging**
